source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "jekyll-paginate-v2", "~> 3.0"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-sitemap", "~> 1.4"
gem "webrick", "~> 1.8"
gem "premonition", "~> 4.0"
gem "h2o-ac-jekyll-extlinks", "~> 0.0"
gem "nokogiri"
