// AUTO-GENERATED by scripts/fetch-notion-diary.mjs — do not edit by hand.
// Source of truth: the diary Notion database. Run `npm run sync:diary` to refresh.
import type { LocalizedText } from '../lib/localized';

/** Free-form — comes from whatever value you use in the Notion "Category" select. */
export type LifeCategory = string;

export interface LifeEvent {
  id: string;
  year: number;
  month: number;
  day: number;
  title: LocalizedText;
  /** Markdown source (from Notion, via notion-to-md). Rendered with <MarkdownContent>. */
  description: LocalizedText;
  category: LifeCategory;
  imageUrl?: string;
}

export const lifeEvents: LifeEvent[] = [
  {
    id: "notion-390e2eb1-2d4d-8004-a335-d1f095b043b5",
    year: 2026,
    month: 1,
    day: 17,
    title: {
      en: "2026.01.07 阴阴阴好像要下雨但是没带伞不过因为开会加了点班就错过了雨的完蛋工作日",
    },
    description: {
      en: "前记：今天是这个专题创建的第一天。能做出这样的努力其实我也下了很大的决心。AI时代令我已经感觉到我不再拥有中学时代的强大的表达能力。和朋友聊天的时候朋友也经常会对我的所说所写感到困惑。当文字不再直抒胸臆时，我们便失去了和世界交流最有力的手段。我们不再能绵里藏针，也不再能直抒胸臆。更无法明修栈道，也不能暗度陈仓。语言表达能力是我认为作为一个成年人最应当具备的能力，也是最多人所缺失掉的能力。所以针对自己的写作，也就是表达能力的练习变得至关重要。曾经自己看不起的八百字的作文，成为了在人工智能时代救赎自己已经堙灭的写作能力最好的方式。\n\n\n## 新年的氛围与归乡的不适 - 启程前\n\n\n早在去年9月时分，便和家里人商量好买了新年过年回程的机票。当机票买定的一刹那，看着晚上九点起飞夜里一点到家的“完美机票”，心里不禁暗喜。虽说同年五月结束了新公司入职研修的我刚刚回过一次家，加之在天气最炎热的盂兰盆节时分全家人在东京及其周边周游了十天，与家里人上次见面并没有很久，但体感却已不再诚实。度过了漫长的红叶季的我心里只有一个念头：赶紧回家。期待着品国内美食，盼望着与家人团聚，期许着同朋友举杯，终于到了回家的那天。\n\n\n由于中日政策的不稳定导致航班大量取消的事态终归影响到了我。从订机票到成功回国的前日，机票足足变更了3次。最后不得已请了一天带薪休假，变更过后航班不再是早归晚回，而是变成了晚归早回的下午回国早上返日的航班。回国那天的航班虽是在黄昏时分，但清晨我便等不及，拎着行李箱踏上了规程。常言之，归心似箭，想必那时的我已经生动地诠释了这个词的含义。回家路上一身轻松，仅有一个白色中号行李箱同行。虽说行李箱中已经装满了回国给家人和朋友带的小礼物，可我却觉得还是差点什么。“是不是还能再买点什么”的想法在我脑中挥之不去。抱着这样的心情，早上九点就早早踏上了去关西机场的电车。（明日续）",
    },
    category: "Diary",
  },
];
