// AUTO-GENERATED by scripts/fetch-notion-diary.mjs — do not edit by hand.
// Source of truth: the diary Notion database. Run `npm run sync:diary` to refresh.
import type { LocalizedText } from '../lib/localized';

/** Free-form — comes from whatever value you use in the Notion "Category" select. */
export type LifeCategory = string;

export interface LifeEvent {
  id: string;
  year: number;
  month: number;
  day: number;
  title: LocalizedText;
  /** Markdown source (from Notion, via notion-to-md). Rendered with <MarkdownContent>. */
  description: LocalizedText;
  category: LifeCategory;
  imageUrl?: string;
}

export const lifeEvents: LifeEvent[] = [];
